name: PULL REQUEST Reward

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  praise-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Praise the person who pushed
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          COMMIT_MESSAGE: ${{ github.event.pull_request.head.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PRAISE_MESSAGES=(
            "Pushお疲れ様でした！"
            "お疲れ様でした！引き続き頑張りましょう。"
            "いいPushですね。レビューを待ちましょう。"
          )
          RANDOM_MESSAGE=${PRAISE_MESSAGES[$((RANDOM % ${#PRAISE_MESSAGES[@]}))]}

          # コミットメッセージの取得をする。（同期時はhead_refから取得する）
          if [[ "${{ github.event.action }}" == "synchronize" ]]; then
            COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          fi

          COMMENT_BODY="🎊 **${RANDOM_MESSAGE}**\n\n"
          COMMENT_BODY+="**${PR_TITLE}**\n"

          # コミットメッセージが取得できたら追加
          if [[ -n "$COMMIT_MESSAGE" ]]; then
            COMMENT_BODY+="**最新のコミット:**\n> ${COMMIT_MESSAGE}\n"
          fi

          # ghコマンドでPRにコメントを投稿
          echo "$COMMENT_BODY" | gh pr comment $PR_NUMBER --body-file -
